# Generated by Django 4.2.5 on 2023-12-30 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='pincode',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)]),
        ),
    ]
